name: Deploy to firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Firebase'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install firebase cli
        run: npm install -g firebase-tools

      - name: Dependency Install
        run: npm ci

      - name: Build Project
        run: npm build

      - name: Deploy to firebase hostring
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
